import Bot from "@/Components/EyeBot/Bot";
import Typewritter from "@/utility/typewritter-effect/Main-Contents";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`page ${styles["main-div"]}`} id="page">
        {/* <MainLoader /> */}
        <video
          className={styles.background}
          // controls={false}
          height="100%"
          width="100%"
          loop
          autoPlay
          muted
        >
          <source type="video/mp4" src={"./black-circle.mp4"} />
        </video>

        <div className={styles.row}>
          <div className={styles.content}>
            <h1>
              <span
                className={`${styles["split-text"]} ${styles["text-hello"]}`}
              >
                HELLO THERE 👋 I'M,
              </span>
              <span
                className={`${styles["split-text"]} ${styles["text-name"]}`}
              >
                Srijan Shankar
              </span>
              <span
                className={`${styles["split-text"]} ${styles["text-name"]}`}
              >
                Dubey
              </span>
              <sapn
                className={`${styles["split-text"]} ${styles["text-about"]}`}
              >
                I work as <Typewritter />
              </sapn>
            </h1>
            <p
              className={`${styles["split-text"]} ${styles["text-paragraph"]} ${styles["text-paragraph-l1"]}`}
              style={{ color: "white" }}
            >
              Turning ideas into real life products is my calling.
            </p>
            <p
              className={`${styles["split-text"]} ${styles["text-paragraph"]}`}
            >
              I am an independent creative, IT graduate who likes to craft solid
              and scalable websites with great user experience.
            </p>
            <div className={styles["button-container"]}>
              <a className={styles.button} href="#">
                Contact me
              </a>
              <br />
              <br />
              <a className={styles.button} href="#">
                about me
              </a>
              <span></span>
            </div>
          </div>
          <div className={styles.bot}>
            <Bot />
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
