import Head from "next/head";
import React from "react";
import Header from "../Header/header";
import MainLoader from "../mainLoader/MainLoader";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainLoader />
      <main className={`page main-div`} id="page">
        {children}
      </main>
    </>
  );
};

export default Layout;
